<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>1.1.9583.15490</AssemblyVersion>
    <FileVersion>1.1.9583.15490</FileVersion>
    <PackageIcon>monster editing app1.png</PackageIcon>
    <ApplicationIcon>Resources\ERACreature.ico</ApplicationIcon>
    <StartupObject>ERA_Core.Program</StartupObject>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Users\robbe\Dropbox\devel\DotNet\RRG_code.pfx</AssemblyOriginatorKeyFile>
</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>True</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>True</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyVersionSettings>None.None.DeltaDayStamp.HalfOfSecondsSinceMidnight</AssemblyVersionSettings>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <AssemblyFileVersionSettings>None.None.DeltaDayStamp.HalfOfSecondsSinceMidnight</AssemblyFileVersionSettings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\AttackTypes.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\ERACreature.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Types_Attacks.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Types_Resistance.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Types_SpellLists.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>